// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfFP22uEmzmzqy2eKxXDeOpdE0swmwJTA',
    appId: '1:984320154803:web:476f1a503fc4123f9fa4c6',
    messagingSenderId: '984320154803',
    projectId: 'marker-finder-834f6',
    authDomain: 'marker-finder-834f6.firebaseapp.com',
    storageBucket: 'marker-finder-834f6.firebasestorage.app',
    measurementId: 'G-B5WWND2H9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa_ztJMzS0igz-ugfQ5el6by5te_R-ktM',
    appId: '1:984320154803:android:cb4734fbd70a5cec9fa4c6',
    messagingSenderId: '984320154803',
    projectId: 'marker-finder-834f6',
    storageBucket: 'marker-finder-834f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvhSG3Lx0OTUST1YAvHe7e2cAgKX96Rg8',
    appId: '1:984320154803:ios:a6dfedc51b9d7b399fa4c6',
    messagingSenderId: '984320154803',
    projectId: 'marker-finder-834f6',
    storageBucket: 'marker-finder-834f6.firebasestorage.app',
    iosBundleId: 'com.example.csvTesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvhSG3Lx0OTUST1YAvHe7e2cAgKX96Rg8',
    appId: '1:984320154803:ios:a6dfedc51b9d7b399fa4c6',
    messagingSenderId: '984320154803',
    projectId: 'marker-finder-834f6',
    storageBucket: 'marker-finder-834f6.firebasestorage.app',
    iosBundleId: 'com.example.csvTesting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfFP22uEmzmzqy2eKxXDeOpdE0swmwJTA',
    appId: '1:984320154803:web:391dc8e8d70d94679fa4c6',
    messagingSenderId: '984320154803',
    projectId: 'marker-finder-834f6',
    authDomain: 'marker-finder-834f6.firebaseapp.com',
    storageBucket: 'marker-finder-834f6.firebasestorage.app',
    measurementId: 'G-XTDZZF5BE5',
  );
}
